/**
 * Event Store Interface
 * Provides pluggable storage abstraction for audit trail event streams.
 * Supports in-memory and persistent storage backends.
 */

import type {
  IntakeEvent,
  IntakeEventType,
  Actor,
} from "../types/intake-contract.js";

// =============================================================================
// § Event Query Filters
// =============================================================================

/**
 * Filters for querying events from the event store.
 * All filters are optional and can be combined.
 */
export interface EventFilters {
  /** Filter by event types. Empty array or undefined means all types. */
  types?: IntakeEventType[];
  /** Filter by actor kind (agent, human, system). Undefined means all actors. */
  actorKind?: Actor["kind"];
  /** Only events on or after this timestamp (ISO 8601). Inclusive. */
  since?: string;
  /** Only events before or on this timestamp (ISO 8601). Inclusive. */
  until?: string;
}

// =============================================================================
// § Event Store Statistics
// =============================================================================

/**
 * Statistics about the event store.
 * Useful for monitoring, debugging, and capacity planning.
 */
export interface EventStoreStats {
  /** Total number of events stored across all submissions */
  totalEvents: number;
  /** Number of unique submissions with events */
  submissionCount: number;
  /** Timestamp of the oldest event in the store (ISO 8601) */
  oldestEvent?: string;
  /** Timestamp of the newest event in the store (ISO 8601) */
  newestEvent?: string;
}

// =============================================================================
// § Event Store Interface
// =============================================================================

/**
 * Pluggable storage backend for audit trail event streams.
 *
 * Events are append-only and immutable. Once written, they cannot be
 * modified or deleted (except through bulk cleanup operations).
 *
 * Implementations must:
 * 1. Guarantee append-only semantics (events never modified after write)
 * 2. Preserve event order within a submission (ordered by timestamp)
 * 3. Support efficient querying by submission ID
 * 4. Support filtering by event type, actor, and time range
 * 5. Handle concurrent writes safely (multiple events appended simultaneously)
 *
 * Available implementations:
 * - InMemoryEventStore: Development/testing with in-memory storage
 * - (Future) DatabaseEventStore: Production with persistent database storage
 * - (Future) S3EventStore: Archival storage with S3-compatible object storage
 */
export interface EventStore {
  /**
   * Append a new event to the store.
   *
   * Events are immutable once appended. The event must have:
   * - Unique eventId (generated by caller)
   * - Valid submissionId
   * - ISO 8601 timestamp in ts field
   * - Valid event type and actor
   *
   * @param event The event to append
   * @throws If event validation fails (duplicate eventId, invalid format, etc.)
   */
  appendEvent(event: IntakeEvent): Promise<void>;

  /**
   * Get all events for a submission, optionally filtered.
   *
   * Events are returned in chronological order (oldest first).
   * Filters are applied server-side for efficiency.
   *
   * @param submissionId The submission ID to query
   * @param filters Optional filters to narrow results
   * @returns Array of events matching the query (empty if submission not found)
   */
  getEvents(
    submissionId: string,
    filters?: EventFilters
  ): Promise<IntakeEvent[]>;

  /**
   * Get store statistics.
   *
   * Useful for monitoring and capacity planning.
   * Implementation may be approximate for performance reasons.
   *
   * @returns Statistics about the event store
   */
  getStats(): Promise<EventStoreStats>;

  /**
   * Clean up old events for storage maintenance.
   *
   * Removes events older than the specified age.
   * Use with caution - this is the only operation that deletes events.
   *
   * Typical use cases:
   * - Regulatory retention limits (e.g., delete events older than 7 years)
   * - Development/testing cleanup
   * - Storage capacity management
   *
   * @param olderThanMs Age threshold in milliseconds (events older than this are deleted)
   * @returns Number of events deleted
   */
  cleanupOld(olderThanMs: number): Promise<number>;
}
