/**
 * Storage Backend Interface
 * Provides pluggable storage abstraction for file upload handling.
 * Supports local filesystem and S3-compatible storage providers.
 */

// =============================================================================
// § Upload Constraints
// =============================================================================

/**
 * Constraints applied to file uploads.
 * Enforced at both URL generation time and upload verification.
 */
export interface UploadConstraints {
  /** Maximum file size in bytes. Must be positive. */
  maxSize: number;
  /** Allowed MIME types. Empty array means any type allowed. */
  allowedTypes: string[];
  /** Maximum number of files that can be uploaded for this field. Must be >= 1. */
  maxCount: number;
}

// =============================================================================
// § Signed Upload URL
// =============================================================================

/**
 * HTTP method allowed for the upload.
 * Most storage backends use PUT for presigned URLs.
 */
export type UploadMethod = 'PUT' | 'POST';

/**
 * A signed URL for direct-to-storage file upload.
 * Generated by the storage backend with embedded constraints and expiration.
 */
export interface SignedUploadUrl {
  /** The presigned URL clients upload to directly */
  url: string;
  /** HTTP method to use for the upload */
  method: UploadMethod;
  /** Required HTTP headers for the upload (e.g., Content-Type) */
  headers?: Record<string, string>;
  /** When this URL expires (ISO 8601 timestamp) */
  expiresAt: string;
  /** Unique identifier for tracking this upload */
  uploadId: string;
  /** Constraints that will be enforced on upload */
  constraints: UploadConstraints;
}

// =============================================================================
// § Upload Metadata
// =============================================================================

/**
 * Metadata about an uploaded file.
 * Returned after successful upload verification.
 */
export interface UploadedFile {
  /** Unique identifier for this upload (matches SignedUploadUrl.uploadId) */
  uploadId: string;
  /** Original filename provided by client */
  filename: string;
  /** MIME type of the uploaded file */
  mimeType: string;
  /** Size of the uploaded file in bytes */
  size: number;
  /** Storage backend specific location identifier */
  storageKey: string;
  /** When the upload was completed (ISO 8601 timestamp) */
  uploadedAt: string;
}

// =============================================================================
// § Upload Status
// =============================================================================

/**
 * Status of an upload operation.
 */
export type UploadStatus = 'pending' | 'completed' | 'failed' | 'expired';

/**
 * Result of checking upload status.
 */
export interface UploadStatusResult {
  /** Current status of the upload */
  status: UploadStatus;
  /** File metadata if upload is completed */
  file?: UploadedFile;
  /** Error message if upload failed */
  error?: string;
}

// =============================================================================
// § Storage Backend Interface
// =============================================================================

/**
 * Pluggable storage backend for file uploads.
 *
 * Implementations must:
 * 1. Generate signed URLs with embedded constraints
 * 2. Support direct client-to-storage uploads (no proxy through FormBridge)
 * 3. Track upload completion and validate constraints
 * 4. Provide file metadata retrieval
 *
 * Available implementations:
 * - LocalStorageBackend: Development/testing with local filesystem
 * - S3StorageBackend: Production with S3-compatible object storage
 */
export interface StorageBackend {
  /**
   * Generate a signed URL for direct file upload.
   *
   * The URL must:
   * - Expire after a reasonable time (recommended: 15-60 minutes)
   * - Enforce size and MIME type constraints if backend supports it
   * - Be single-use (one file per URL)
   *
   * @param params Upload parameters
   * @returns Signed upload URL with constraints
   */
  generateUploadUrl(params: {
    /** Unique identifier for the intake form */
    intakeId: string;
    /** Unique identifier for the submission */
    submissionId: string;
    /** Field path this upload is for (e.g., "docs.w9") */
    fieldPath: string;
    /** Original filename from client */
    filename: string;
    /** MIME type from client */
    mimeType: string;
    /** Upload constraints to enforce */
    constraints: UploadConstraints;
  }): Promise<SignedUploadUrl>;

  /**
   * Verify that an upload has completed successfully.
   *
   * Must check:
   * - File exists at the storage location
   * - File size is within constraints
   * - MIME type matches constraints (if verifiable)
   *
   * @param uploadId The upload ID from generateUploadUrl
   * @returns Upload status and file metadata
   */
  verifyUpload(uploadId: string): Promise<UploadStatusResult>;

  /**
   * Get metadata for a previously completed upload.
   *
   * @param uploadId The upload ID
   * @returns File metadata or undefined if not found
   */
  getUploadMetadata(uploadId: string): Promise<UploadedFile | undefined>;

  /**
   * Generate a signed URL for downloading a previously uploaded file.
   *
   * @param uploadId The upload ID
   * @param expiresInSeconds How long the URL should be valid (default: 3600)
   * @returns Signed download URL or undefined if file not found
   */
  generateDownloadUrl(
    uploadId: string,
    expiresInSeconds?: number
  ): Promise<string | undefined>;

  /**
   * Delete an uploaded file from storage.
   *
   * @param uploadId The upload ID
   * @returns True if deleted, false if not found
   */
  deleteUpload(uploadId: string): Promise<boolean>;

  /**
   * Clean up expired upload URLs and associated temporary storage.
   *
   * Should be called periodically to remove:
   * - Expired but unused upload URLs
   * - Failed upload attempts
   * - Orphaned temporary files
   */
  cleanupExpired(): Promise<void>;
}
